import "./globals.css";
import type { Metadata } from "next";
import Providers from "@/lib/providers";

export const metadata: Metadata = {
  title: "Pasifika",
  description: "Generated by create dynamic app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ fontFamily: 'system-ui, sans-serif' }}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}